# Generated by Django 5.2.8 on 2025-11-30 22:10

import images.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(help_text='Nom original du fichier uploadé', max_length=255)),
                ('original_file', models.ImageField(help_text='Fichier image original stocké sur le serveur', upload_to=images.models.upload_path)),
                ('original_size', models.PositiveIntegerField(help_text='Taille du fichier original en octets')),
                ('webp_file', models.ImageField(blank=True, help_text='Version optimisée au format WebP (compression élevée)', null=True, upload_to='webp/')),
                ('thumbnail', models.ImageField(blank=True, help_text="Miniature de l'image (200x200px max)", null=True, upload_to='thumbnails/')),
                ('blur_placeholder', models.TextField(blank=True, help_text="Version très légère floutée encodée en base64 pour l'affichage immédiat")),
                ('width', models.PositiveIntegerField(default=0, help_text="Largeur de l'image en pixels")),
                ('height', models.PositiveIntegerField(default=0, help_text="Hauteur de l'image en pixels")),
                ('format', models.CharField(default='JPEG', help_text="Format de l'image original (JPEG, PNG, etc.)", max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date et heure de création de l'enregistrement")),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date et heure de dernière modification')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
